# Generated by Django 4.0.4 on 2022-06-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state1', models.CharField(blank=True, max_length=200, null=True)),
                ('state2', models.CharField(blank=True, max_length=200, null=True)),
                ('state3', models.CharField(blank=True, max_length=200, null=True)),
                ('state4', models.CharField(blank=True, max_length=200, null=True)),
                ('state5', models.CharField(blank=True, max_length=200, null=True)),
                ('state6', models.CharField(blank=True, max_length=200, null=True)),
                ('state7', models.CharField(blank=True, max_length=200, null=True)),
                ('state8', models.CharField(blank=True, max_length=200, null=True)),
                ('state9', models.CharField(blank=True, max_length=200, null=True)),
                ('state10', models.CharField(blank=True, max_length=200, null=True)),
                ('state11', models.CharField(blank=True, max_length=200, null=True)),
                ('state12', models.CharField(blank=True, max_length=200, null=True)),
                ('state13', models.CharField(blank=True, max_length=200, null=True)),
                ('state14', models.CharField(blank=True, max_length=200, null=True)),
                ('state15', models.CharField(blank=True, max_length=200, null=True)),
                ('state16', models.CharField(blank=True, max_length=200, null=True)),
                ('state17', models.CharField(blank=True, max_length=200, null=True)),
                ('state18', models.CharField(blank=True, max_length=200, null=True)),
                ('state19', models.CharField(blank=True, max_length=200, null=True)),
                ('state20', models.CharField(blank=True, max_length=200, null=True)),
                ('state21', models.CharField(blank=True, max_length=200, null=True)),
                ('state22', models.CharField(blank=True, max_length=200, null=True)),
                ('state23', models.CharField(blank=True, max_length=200, null=True)),
                ('state24', models.CharField(blank=True, max_length=200, null=True)),
                ('state25', models.CharField(blank=True, max_length=200, null=True)),
                ('state26', models.CharField(blank=True, max_length=200, null=True)),
                ('state27', models.CharField(blank=True, max_length=200, null=True)),
                ('state28', models.CharField(blank=True, max_length=200, null=True)),
                ('state29', models.CharField(blank=True, max_length=200, null=True)),
                ('state30', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_or_preg_type', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('video_url', models.CharField(default='http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocProject.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_id', models.ImageField(blank=True, default='doc_img/profile.png', null=True, upload_to='upload_id/')),
                ('working_location', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_img', models.ImageField(default='doc_img/profile.png', upload_to='doc_img/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.CharField(blank=True, max_length=500, null=True)),
                ('appointment_url', models.CharField(blank=True, max_length=500, null=True)),
                ('isdoctorcompleted', models.BooleanField(default=False)),
                ('url_password', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocProject.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocProject.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.CharField(blank=True, max_length=500, null=True)),
                ('appointment_url', models.CharField(blank=True, max_length=500, null=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocProject.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocProject.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AskQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocProject.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocProject.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.CharField(blank=True, max_length=500, null=True)),
                ('appointment_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ispatientcompleted', models.BooleanField(default=False)),
                ('url_password', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocProject.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocProject.patient')),
            ],
        ),
    ]
