# Generated by Django 4.0.4 on 2022-06-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
