# Generated by Django 4.0.4 on 2022-06-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0006_transaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DocProject.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DocProject.doctor'),
            preserve_default=False,
        ),
    ]
