# Generated by Django 4.0.5 on 2022-06-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0011_patient_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
