# Generated by Django 4.0.5 on 2022-06-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0012_doctor_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
