# Generated by Django 4.0.5 on 2022-06-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0013_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='working_location',
            new_name='working_location1',
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_location2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_location3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_location4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_location5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
