# Generated by Django 4.0.5 on 2022-06-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0014_rename_working_location_doctor_working_location1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_img',
            field=models.ImageField(default='profile.png', upload_to='doc_img/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='upload_id',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='upload_id/'),
        ),
    ]
