# Generated by Django 4.0.5 on 2022-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0018_alter_doctor_doc_img_alter_doctor_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='latitude_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude_1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
