# Generated by Django 4.0.5 on 2022-07-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0019_doctor_latitude_1_doctor_longitude_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude_2', models.FloatField(blank=True, max_length=200, null=True)),
                ('latitude_2', models.FloatField(blank=True, max_length=200, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocProject.patient')),
            ],
        ),
    ]
