# Generated by Django 4.0.5 on 2022-07-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0020_patient_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_location1_img',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='working_location1_img/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_location2_img',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='working_location2_img/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_location3_img',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='working_location3_img/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_location4_img',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='working_location4_img/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_location5_img',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='working_location5_img/'),
        ),
    ]
