# Generated by Django 4.0.5 on 2022-07-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0021_doctor_working_location1_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='working_location1_img',
        ),
    ]
