# Generated by Django 4.0.5 on 2022-07-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0022_remove_doctor_working_location1_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='upload_id',
            field=models.ImageField(blank=True, default='static/profile.png', null=True, upload_to='upload_id/'),
        ),
    ]
