# Generated by Django 4.0.5 on 2022-07-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocProject', '0023_alter_doctor_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_img',
            field=models.ImageField(blank=True, null=True, upload_to='doc_img/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='upload_id',
            field=models.ImageField(blank=True, null=True, upload_to='upload_id/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_location2_img',
            field=models.ImageField(blank=True, null=True, upload_to='working_location2_img/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_location3_img',
            field=models.ImageField(blank=True, null=True, upload_to='working_location3_img/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_location4_img',
            field=models.ImageField(blank=True, null=True, upload_to='working_location4_img/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_location5_img',
            field=models.ImageField(blank=True, null=True, upload_to='working_location5_img/'),
        ),
    ]
